version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: eshop-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passer
      POSTGRES_DB: microservice_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - eshop-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5


  produit-service:
    build: ./produit
    container_name: produit-service
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - eshop-network

  utilisateur-service:
    build: ./utilisateur
    container_name: utilisateur-service
    ports:
      - "8082:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - eshop-network

  nginx:
    image: nginx:latest
    container_name: eshop-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - produit-service
      - utilisateur-service
    networks:
      - eshop-network

volumes:
  postgres_data:

networks:
  eshop-network:
    driver: bridge
